### PR TITLE
feat: PR-Workflow

### PR DESCRIPTION
**Pull request by ansibleguy**
Greetings!

This PR create a GitHub workflow to run basic tests on PR-creation.

This helps PR-owners and Repository-Maintainers to get a quick overview of the PR quality.

### CODE REVIEW

**Comment by ansibleguy** [comment]
Related to: https://github.com/ansible-semaphore/semaphore/issues/1356

**Comment by fiftin** [comment]
Hi @ansibleguy can we do all tests for PR?

**Comment by fiftin** [comment]
Added PRs to DEV workflow, thank you!

**Comment by ansibleguy** [comment]
Nice!

**Pull request closed without merging**
