### PR TITLE
feat: refactoring of alerts and send correct email alerts

### LINKED ISSUE #1571: Email alerts for docker images don't work anymore
Hello guys,

after the update from 2.9.23 to 2.9.37 the email notifications for docker images don't work anymore.
When a task failed no email alert or something else is shown in the task window.

Also no logs will be shown in container.
It seems that the container don't do nothing in background after the task failed.
I also tested the two images after 2.9.37 but there the issue also apear.
I wish i can post logs but there are no entry that show anything to relate to this issue.

### LINKED ISSUE #1627: Slack notifications not working
I've configured Slack in Semaphore:
```
"slack_alert": true,
"slack_url": "https://slackWebhook/abcd",
```

I've enabled alerts everywhere I could find a checkbox in the UI:
"Allow alerts for this project" set on the project.
"Send alerts" is set for the user. 
The task does NOT have to be "Suppress success alerts" checked. 

But still no notification sent when a task succeeds.

I am running version 2.9.37 in a container on Linux (Rocky 9.2). 
A curl command to the same webhook from within the container is successful. 

Any ideas what could be wrong or any diagnostics I can check to investigate this further?
Thanks

### LINKED ISSUE #1782: Email header incomplete
semaphore version: v2.9.52-beta
OS: Linux 6.1.0-18-amd64 (Debian 12.5) 
---

I have the problem de mails from semaphore because on my spam filter.

although mails from within my network don't have to match all the strict mail requirement's external mail's have to, the mail still have to be an valid e-mail, with isn't the case:
```
BAD HEADER SECTION: Missing required header field: "Date"
```
so, is it possible to add the `Date` header to the semaphore mail notifications?

The full mail header:
```
X-Envelope-From: [...]
X-Envelope-To: [...]
X-Envelope-To-Blocked: 
X-Quarantine-ID: <oYJ2mUM5ZAZY>
X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "Date"
X-Spam-Flag: NO
X-Spam-Score: -0.022
X-Spam-Level: 
X-Spam-Status: No, score=-0.022 tag=x tag2=x kill=x tests=[ALL_TRUSTED=-1,
	BAYES_00=-1.9, MISSING_DATE=1.36, MISSING_HEADERS=1.021,
	MISSING_MID=0.497] autolearn=no autolearn_force=no
Received: [...]
Received: [...]
Subject: Task '[...]' failed
From: [...]
```
(all the `[...]` parts i have striped.)

### PR DESCRIPTION
**Pull request by tboerger**
Previously the sent email alerts have been missing mandatory headers like `Date` and it was also missing content type, content transfer encoding and mime version. I have taken proper examples form the unmaintained gomail library to build right emails.

Besides that I have refactored the calls for alerts, they git the same structure now and it should be prepared to inject custom templates for all altering methods at some later point. Generally it is prepared for a more flexible alert handling.

Fixes https://github.com/ansible-semaphore/semaphore/issues/1782
Fixes https://github.com/ansible-semaphore/semaphore/issues/1627
Fixes #1571 

Replaces https://github.com/ansible-semaphore/semaphore/pull/1771
Replaces https://github.com/ansible-semaphore/semaphore/pull/1636

### CODE REVIEW

**Comment by samerbahri98** [comment]
I am not convinced this is a refactor for alerts. As the main issues with the initial alerts implementation (being tightly coupled to the currently supported alerts, making it very hard to support any other alerting mechanism for now) are still there. This change should be considered as a bug fix and not a refactor (ie: maybe the title and the description of this pull request should be slightly changed).

That being said, I still think that this pull request should be reviewed and merged, for the purpose of fixing the mentioned bugs, and to serve as a functional starting point for a refactor. Either way, I am not a maintainer, so make of my opinion what you want.

**Comment by tboerger** [comment]
The code have been still refactored, not just fixed. Is it more flexible than before? No, not yet.

**Comment by fiftin** [comment]
@tboerger did you test it?

**Comment by tboerger** [comment]
I have tested the mail alerts with mailhog as a target and it contains all the mandatory fields like To, Date and so on.

**Comment by tboerger** [comment]
Looks like I got to resolve conflicts anyway as the teams integration have been merged.

**Pull request merged**
