### PR TITLE
fix(integrations): Use payload instead of re-reading closed Body

### PR DESCRIPTION
**Pull request by andreas-marschke**
Since `r.Body` was already consumed at the start of the Handler, the Body nil'ed on extraction.
This change carries the payload through to extraction to extract values correctly.

Also with this MR, the UI presents the fact that a Task was started by Integration through the TaskLogView.

### CODE REVIEW

**Review by tboerger — APPROVED** [review]

**Comment by reisenbauer** [comment]
@tboerger - could you please merge this request? thx

**Comment by tboerger** [comment]
I can only handle issues and discussions, no write access to the repo.

**Comment by reisenbauer** [comment]
@fiftin any chance to get this merged?

**Comment by tboerger** [comment]
This PR is already merged?

**Comment by reisenbauer** [comment]
Mea culpa, was my fault - doing it right just works :D

**Pull request merged**
