### PR TITLE
Support unified requirements.yml for galaxy collections

### PR DESCRIPTION
**Pull request by andreas-marschke**
This changeset provides support to find `ansible-galaxy` collection `requirements.yml` relative to repo path, in the `collections/` directory. This supports inventory organisations where only one requirements.yml is set up for the entire repo.

This partially resolves issues reported here: ansible-semaphore/semaphore#1144

### CODE REVIEW

**Comment by andreas-marschke** [comment]
@fiftin Anything stopping this from being code-reviewed/merged?

**Comment by fiftin** [comment]
Hi @andreas-marschke 

I'm here :) I reviewing.

**Comment by rwaffen** [comment]
is this still a thing? 
i'm on v2.9.16 and still having the problem that $repository/collections/requirements.yml is ignored :(

**Comment by andreas-marschke** [comment]
@rwaffen As it hasn't been merged yet, I don't think it's resolved.

**Comment by rwaffen** [comment]
it's a pitty. but how do you handle this as long this is not merged, is there a workaround for this?

**Comment by stefanux** [comment]
@rwaffen defining two requirement-files is the way to go and working (in 2.8.90, tested again with latest version 2.9.4):
roles/requirements.yml
collections/requirements.yml

minimal example for collections:
```
---
collections:
  - name: community.general
```
requirements are cached and only refreshed if file(s) are changed: "roles/requirements.yml has no changes. Skip galaxy install process.".
if you experience problems see output of semaphore and make another issue since this is a feature issue.

**Comment by RusticPotatoes** [comment]
any updates on getting this pr merged?  @stefanux can help testing if needed

**Comment by steadfasterX** [comment]
@fiftin any update on that one?

**Comment by smooth-baking-powder** [comment]
Any Updates?

**Comment by fiftin** [comment]
Hi, 
I'm sorry @andreas-marschke I missed this PR. Looks like I did what you want.

image

**Comment by fiftin** [comment]
@steadfasterX , @corincorvus could you please check this in latest release?

**Comment by alexbarton** [comment]
@fiftin, looks like a unified requirements.yml file in the root directory of the project is not yet supported, right? But this   would be really great! :wink:

Do you think you could possibly enhance this by adding the `<project_root>/requirements.yml` path to the search path, for collections as well as roles?

This would enable us to follow the structure outlined in the Ansible documentation here:
[Installing roles and collections from the same requirements.yml file](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file)

Thanks for all your work!
Alex

**Comment by DeadNews** [comment]
Yes.

[Ansible-lint config for example](https://github.com/ansible/ansible-lint/blob/1dbb602151e506fd324ac8fe41dededd31f56087/docs/usage.md#dependencies-and-requirements):

> Valid locations for these files are:
> 
> - [`requirements.yml`](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file)
> - `roles/requirements.yml`
> - `collections/requirements.yml`

**Comment by DeadNews** [comment]
@alexbarton
Yes.

[Ansible-lint config for example](https://github.com/ansible/ansible-lint/blob/1dbb602151e506fd324ac8fe41dededd31f56087/docs/usage.md#dependencies-and-requirements):

> Valid locations for these files are:
> 
> - [`requirements.yml`](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file)
> - `roles/requirements.yml`
> - `collections/requirements.yml`

**Comment by deadnews** [comment]
@alexbarton
Yes.

[Ansible-lint docs for example](https://github.com/ansible/ansible-lint/blob/1dbb602151e506fd324ac8fe41dededd31f56087/docs/usage.md#dependencies-and-requirements):

> Valid locations for these files are:
> 
> - [`requirements.yml`](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file)
> - `roles/requirements.yml`
> - `collections/requirements.yml`

**Comment by steadfasterX** [comment]
> @fiftin, looks like a unified requirements.yml file in the root directory of the project is not yet supported, right? But this would be really great! 😉
> 
> Do you think you could possibly enhance this by adding the `<project_root>/requirements.yml` path to the search path, for collections as well as roles?
> 
> This would enable us to follow the structure outlined in the Ansible documentation here: [Installing roles and collections from the same requirements.yml file](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file)
> 
> Thanks for all your work! Alex

@fiftin this ^^^ would be what I expected to be honest. I usually create 1 requirements.yml and place collections and roles both within.. would be great to have that supported, e.g. by the suggested  approach using a requirements.yml directly in the root path..

**Comment by fiftin** [comment]
Hi @andreas-marschke sorry for delay, the feature has been implemented (without using additional common function `installGalaxyRequirementsFile`).

**Comment by deadnews** [comment]
@fiftin
Dependencies from `<project_root>/requirements.yml` are not picked up.

The old paths also no longer work:
* `<project_root>/roles/requirements.yml`
* `<project_root>/collections/requirements.yml`

The dependency installation process is broken in `v2.10.32`.

**Comment by juju4** [comment]
from code (https://github.com/semaphoreui/semaphore/blob/develop/db_lib/AnsibleApp.go#L135), it seems both are supported and should be in since 2.10.32.
In my test run with 2.10.43, repo/requirements.yml only appears on roles check and not processed if no changes which is an issue on first execution.
```
No /tmp/semaphore/repository_1_1/collections/requirements.yml file found. Skip galaxy install process.
Skipping install, no requirements found
No /tmp/semaphore/repository_1_1/roles/requirements.yml file found. Skip galaxy install process.
/tmp/semaphore/repository_1_1/requirements.yml has no changes. Skip galaxy install process.
```
Ideally, it should be able to customize requirements path by semaphore tasks or repo.
I don't know if there is an agreed standard on where file should be, especially more in a context where not using collections structure...

Also, for some reasons, semaphore user home path is not included in tasks role_path, only getting <repo>/roles, <repo>, and whatever included in <repo>/ansible.cfg which may be relevant or not to a semaphore run. So you can't pre-install dependencies.

**Pull request closed without merging**
