### PR TITLE
Rearrange list of Task Template, Inventory, Environment, Team in UI

### LINKED ISSUE #260: Allow rearrage of lists in UI (Task Templates, Inventory, etc)
This would be useful in big projects.

### PR DESCRIPTION
**Pull request by laeshiny**
Fix #260

### CODE REVIEW

**Comment by ericlakich** [comment]
+1 for this PR.

**Comment by Echobob** [comment]
👍 Thanks

**Comment by laeshiny** [comment]
Thanks:)

**Comment by ericlakich** [comment]
thanks!!

**Pull request merged**
