### PR TITLE
Write a key pair by identity name

### PR DESCRIPTION
**Pull request by rmessner**
Avoid to rewrite all the time the default private/public key of the user running semaphore by creating a keypair by identity.

### CODE REVIEW

**Comment by matejkramny** [comment]
Hi, thanks!

What if `playbook.identity.name` contains a space or special characters that break the commands, eg causing invalid files?

I feel like there should be another field for if its a private key, what the name of it would be.

Also, semaphore is supposed to run in a sandbox, the key is saved in `~/.ssh/id_rsa` to save complications coming from git (which you've solved in the commit).

They could now be stored in a special dir eg. `~/.semaphore`.

Just a few ideas. Otherwise, thanks for your work!

**Comment by acca301** [comment]
It's a little bit more complex - the whole pullGit.sh/ssh_wrapper.sh concept needs rework.

- the identity may be not RSA, but say, ED25519
- Git repo may be given in a URL form like "ssh://host:port/directory/repo". ssh_wrapper.sh chokes up on that

It sounds like **playbook.identity.name** should be introduced indeed, but with a different than the pull request semantics and pullGit.sh to be retired.

Still scratching my head, can we discuss that?

**Comment by matejkramny** [comment]
@acca301 create a separate issue unless it directly involves this PR.

**Comment by rmessner** [comment]
I closed it because i have no more time to spend on it.

**Pull request closed without merging**
