### PR TITLE
Update semaphore-wrapper

### PR DESCRIPTION
**Pull request by YoungjuWang**
I updated semaphore-wrapper for telegram / slack / email alerts

### CODE REVIEW

**Comment by YoungjuWang** [comment]
@fiftin Can I get a review??

**Comment by fiftin** [comment]
Hi @YoungjuWang , thank you, I reviewing.

**Comment by wschoot** [comment]
It looks to me that the variables for slack are `SLACK_ALERT` and `SLACK_URL`, but this seems indeed to be a missing piece for slacknotifies to work.

**Comment by ff-fgomez** [comment]
+1 on this PR. It's sorely needed in docker deployments

**Comment by Guits32** [comment]
+1 on this PR :+1:  @fiftin 

Thanks a lot for this awesome tool

**Comment by ouafnico** [comment]
+1 on this PR

**Comment by nathandiruggiero** [comment]
+1 on this PR 👍🏽

**Comment by tboerger** [comment]
The whole alerting system will be moved from the coonfiguration into the database which will obsolete this change. But still thank you for taking the effort to extend this script.

**Pull request closed without merging**
