### PR TITLE
Allow override of Task and Template git_branch

### PR DESCRIPTION
**Pull request by Omicron7**
This adds an API option when running a Task to allow overriding the Git Branch used/cloned during the Task execution. It also add the ability to override the Git Branch used by a Template when created with the API. This is useful for running Tasks using a development, or specific release branch of a repository.

Implements #2277

### CODE REVIEW

**Comment by fiftin** [comment]
let's allow null value for this column.

Null value more efficient for heavily used columns in large tables.

**Comment by Omicron7** [comment]
@fiftin Updated to remove the `not null` constraint. I originally just copied the column from the `project__repository` table.

**Comment by fiftin** [comment]
Hi @Omicron7 thank you!

I think we should add ability to choose branch in template too. Not just in task. It will be logically.

**Comment by Omicron7** [comment]
@fiftin I've rebased on the latest `develop` and added the ability to override `git_branch` on a Project Template using the API. LocalJob will preference `git_branch` on the Task over the Template if both are set.

I'll need you to implement, or help if you'd like `git_branch` exposed on the front end for a Template.

**Comment by Omicron7** [comment]
`dredd` tests are passing locally for me using `boltdb`. Not sure why they are failing in GitHub Actions.

```shell
2024-09-17T15:48:55.213Z - debug: Gracefully terminating the hooks handler process
2024-09-17T15:48:55.213Z - debug: Wrapping up testing and waiting until all reporters are done
complete: 76 passing, 0 failing, 0 errors, 16 skipped, 92 total
complete: Tests took 8509ms
```

**Comment by Omicron7** [comment]
@fiftin This should be good to go. I realized the `git_branch` wasn't actually saving to the database, so I fixed that and as well as allowing null.

**Comment by Omicron7** [comment]
@fiftin I've rebased this on the latest `develop` and fixed the merge conflicts. Would it be possible to get this is the next release?

**Comment by Omicron7** [comment]
I am unsure how to fix the Codacy issues.

**Comment by fiftin** [comment]
Hi @Omicron7 sorry for delay,

Codacy is not a problem. I reviewing your PR. Thank you.

**Comment by fiftin** [comment]
Thank you Brian!
merged

**Pull request merged**
