### PR TITLE
fix: Cannot read property 'then' of undefined in templates.update

### PR DESCRIPTION
**Pull request by fiftin**

### CODE REVIEW

**Comment by twhiston** [comment]
@fiftin What is the actual problem it fixes? (from the vague name it's not something that I have encountered). Could you please provide some context of when this happens

@strangeman - have you used this patch at all?

**Comment by fiftin** [comment]
Each time when ```templates.update method``` called. 
```modal.result.then(callback)``` doesn't return instance of ```modal```, it return result of ```callback``` function.

**Comment by twhiston** [comment]
absolutely! Thanks very much for the explanation (i'm not an FE developer and very much appreciate your contributions in this area). I'll get this merged in soon

**Comment by twhiston** [comment]
@fiftin after merging your other pr this now has a conflict, would be awesome if you could fix it and I will merge this straight in

**Comment by fiftin** [comment]
I fix this bug in next pull request

**Pull request closed without merging**
