### PR TITLE
Fix integrations visibility sidebar logic typo

### PR DESCRIPTION
**Pull request by andreas-marschke**
Fixes small typo in the App.vue definition and logic checking for the user data if they are an admin or allowed to use integrations.

### CODE REVIEW

**Comment by andreas-marschke** [comment]
@fiftin Can I submit documentation updates for this somewhere?

**Review by tboerger — APPROVED** [review]

**Comment by fiftin** [comment]
@andreas-marschke https://github.com/semaphoreui/ansible-semaphore-docs

**Comment by andreas-marschke** [comment]
@fiftin Any concerns/qualms to merging it in?

**Comment by fiftin** [comment]
I do this fast. But I don't see your MR

**Comment by andreas-marschke** [comment]
@fiftin I'm asking if there's anything else you need to merge *this* fix.
I want to work on the docs separately.

**Comment by fiftin** [comment]
Hi @andreas-marschke 
it is temporary flag. I will remove it soon.

**Comment by andreas-marschke** [comment]
@fiftin I understand it's temporary. 

I'd just like to deploy a recent `develop` build of the main container with the integrations feature available, so I don't need to have the entire CI & Build setup internally for my systems. It's somewhat time sensitive to us. 

Thanks for the heads up however.

**Comment by fiftin** [comment]
Hi, 
sorry for delay. Flag deleted in `develop`.

**Comment by fiftin** [comment]
@andreas-marschke you can contact me in Telegram in group https://t.me/semaphoreui if you need speed up the process ;)

**Comment by tboerger** [comment]
But do integrations work for non-admin users?

**Pull request closed without merging**
