### PR TITLE
Replaced all ansible-semaphore with semaphoreui

### PR DESCRIPTION
**Pull request by jriberg**
There where alot of references back to the old repo. Even if it works, it looks ugly.
I also added "--no-optional" to npm in the taskfile so development can be done on non-MacOSx hosts too.

### CODE REVIEW

**Comment by fiftin** [comment]
It is very useful PR. Thank you!

**Comment by fiftin** [comment]
Error in latest build:
image

**Comment by jriberg** [comment]
Is that due to the test no clearing the go.mod between runs?

**Comment by fiftin** [comment]
Hi @jriberg I closing this PR because it duplicates your newer PR https://github.com/semaphoreui/semaphore/pull/2357.

**Pull request closed without merging**
