### PR TITLE
Cleanup injected inventory file

### PR DESCRIPTION
**Pull request by pavlozt**
Inventory temp file cleaning

### CODE REVIEW

**Comment by Freebase394** [comment]
What is this ??

Are this files??

image

**Comment by pavlozt** [comment]
@fiftin As you can see, the problem is annoying.

**Comment by fiftin** [comment]
Sorry to long delay. Thanks a lot for your work. Currently the PR is not compatible with the code. I closing it. 

Can you create new PR? If not, I will move your changes to `develop` branch.

**Comment by fiftin** [comment]
@pavlozt do you still use Semaphore?

**Comment by pavlozt** [comment]
@fiftin 
This PR is no longer relevant. Modern versions no longer duplicate temporary inventory files.

**Comment by Freebase394** [comment]
Thanks by the way. Nice work Guys :+1:

**Pull request closed without merging**
