### PR TITLE
Added docker environment variable SEMAPHORE_DB_DIALECT_ID

### PR DESCRIPTION
**Pull request by mwxp06**

### CODE REVIEW

**Comment by mwxp06** [comment]
This add support for new environment variable:
SEMAPHORE_DB_DIALECT_ID

Values, what database to use: 1 or 2 or 3
1 - MySQL
2 - BoltDB
3 - PostgreSQL

**Review by fiftin — CHANGES_REQUESTED** [review]
Could you rename variable to `SEMAPHORE_DB_DIALECT`?

**Comment by mwxp06** [comment]
Yes, no problem, only I think that:
SEMAPHORE_DB_DIALECT
Is word like "MySQL" and 1 is ID for this so better is use SEMAPHORE_DB_DIALECT_ID

What do you think?

**Comment by fiftin** [comment]
> Yes, no problem, only I think that: SEMAPHORE_DB_DIALECT Is word like "MySQL" and 1 is ID for this so better is use SEMAPHORE_DB_DIALECT_ID
> 
> What do you think?

Hm...
May be convert `SEMAPHORE_DB_DIALECT` to ID in `semaphore-wrapper` ? It doesn't seem difficult.

**Comment by mwxp06** [comment]
So your request for change is:
in docker environment user give for example: 
docker-compose.yml
SEMAPHORE_DB_DIALECT: mysql

and then in:
semaphore-wrapper
convert SEMAPHORE_DB_DIALECT: mysql to SEMAPHORE_DB_DIALECT:1, which is passing to config.stdin

**Comment by fiftin** [comment]
Thank you @mwxp06 !

**Pull request merged**
