### PR TITLE
Fix api docs

### PR DESCRIPTION
**Pull request by gsmlg**
#1423

### CODE REVIEW

**Comment by fiftin** [comment]
Hi @gsmlg 

I added GH Actions workflow for testing PRs. But I don't know how to trigger workflow for existing PRs. Can you add some commit? :)

**Comment by gsmlg** [comment]
@fiftin 
I've added new commit.

**Comment by fiftin** [comment]
hi @gsmlg 

You can run Dredd-tests locally by guide: https://github.com/ansible-semaphore/semaphore/blob/develop/CONTRIBUTING.md#how-to-run-dredd-tests-locally


If it is not clean please let me know here ;)

**Comment by gsmlg** [comment]
Sorry for that, it just auto sync the upstream and trigger an action.
The test in my fork is already success, I will find why broken here.

**Pull request merged**
