### PR TITLE
add missing " --recursive"

### PR DESCRIPTION
**Pull request by modoojunko**
add --recursive to support download playbooks which uses git submodule

related issue : #181

### CODE REVIEW

**Comment by matejkramny** [comment]
You should `gofmt` the code!

**Comment by modoojunko** [comment]
@matejkramny Sorry I did not notice the CI does not include gofmt check, could you tell me the gofmt rules?

**Comment by matejkramny** [comment]
Its pretty standard. I didn't configure it any way, basically just put a space after the comma: `"--recursive",t` & it will be ok.

usually you have `gofmt` run after you save a file, along with `goimports` etc.

**Comment by modoojunko** [comment]
@matejkramny Sorry, I'm fresh go coder even I have not go though all the guide.

 I have pushed the fix.

**Comment by matejkramny** [comment]
No worries, thanks for fixing this.

**Pull request merged**
