### PR TITLE
Fix passing arguments and variables to shell apps.

### PR DESCRIPTION
**Pull request by ShaneMcC**
Fixes shell apps not getting any command line arguments.

This is a fix for #2229 

This reverts d617280bc71ffd2fc767b8942fb0989f864d1540 and then adds in the extra missing arguments from Task/Template/Environment

### CODE REVIEW

**Comment by fiftin** [comment]
Hi @ShaneMcC did you test the PR?

**Comment by ShaneMcC** [comment]
Hi @fiftin - Yes.

I have a test setup that sets vars in appropriate places (environment, task, template) and then a script which prints `"${@}"` and `env | grep -v Semaphore_` and it looked like it was working:

```
==========
Args: --SecretExtra=secret --arg1 --arg2 --ExtraVar=value --varOne=1 VAR_TWO=2 --arg3
==========

==========
Env:
==========
HOSTNAME=4bd02ded3dee
ENV_VAR=value
PWD=/tmp/semaphore/repository_1_1
HOME=/tmp/semaphore
VIRTUAL_ENV=/opt/semaphore/apps/ansible/9.4.0/venv
SECRET_ENV=secret
SHLVL=2
ANSIBLE_VERSION=9.4.0
PATH=/opt/semaphore/apps/ansible/9.4.0/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
==========
```

In this case, `--varOne` and `VAR_TWO` are survey vars. `--arg3` is an arg passed to the task, `--arg1` and `--arg2` are part of the template.
`--ExtraVar` and `--SecretExtra` are part of the environment along with `ENV_VAR` and `SECRET_ENV`

**Comment by fiftin** [comment]
Thank you!

**Comment by rdiazjr** [comment]
Hello, is this fix already in the latest docker image?

**Comment by yp-zhu** [comment]
yes, I pull the image from "develop" and worked.

**Pull request merged**
