### PR TITLE
 add Inventory ID  when creating tasks

### PR DESCRIPTION
**Pull request by gaoyue1989**
see https://github.com/semaphoreui/semaphore/issues/2283

https://github.com/semaphoreui/semaphore/blob/cde8515fb13cde353c496bec35f00a336947a219/db/Task.go#L52
I saw that the inventory ID has been defined in the database task table, which means we can pass it in from the API, but it has not been processed in the future. I think we can override the inventory in https://github.com/semaphoreui/semaphore/blob/cde8515fb13cde353c496bec35f00a336947a219/services/tasks/TaskRunner.go#L251-L257 to make this configuration effective

### CODE REVIEW

**Comment by fiftin** [comment]
Hi @gaoyue1989 will old scenario work if user don't provide inventory id in task?

**Comment by gaoyue1989** [comment]
> Hi @gaoyue1989 will old scenario work if user don't provide inventory id in task?



> Hi @gaoyue1989 will old scenario work if user don't provide inventory id in task?

thinks, now the code if i don't provide inventory id in task  is will be use inventory id in template,and if not find inventory id  is also use  inventory id in template

**Comment by fiftin** [comment]
@gaoyue1989 did you test it?

**Comment by gaoyue1989** [comment]
> @gaoyue1989 did you test it?

企业微信截图_3d546207-ae10-4df8-bc24-a1b92fae4730

I add tow test in askRunner_test.go  one is inventory id in task and  one is inventory id is nil in task   
and I also run the changed docker ues api test

**Comment by fiftin** [comment]
Thank you @gaoyue1989 !

**Pull request merged**
