### PR TITLE
ci: update Docker to alpine:3.18 / golang:1.20.5

### PR DESCRIPTION
**Pull request by cedbale**

### CODE REVIEW

**Comment by fiftin** [comment]
Hi @cedbale 

Did you test this?

**Comment by cedbale** [comment]
> Hi @cedbale
> 
> Did you test this?

Semaphore correctly run on my side with this Docker setup.

After having a deeper look into the Alpine version installed within the container. It seems that this is Alpine 3.16 and not 3.18. But that is not what Semaphore binary told. 🤔 So do not really know who to trust.

```
# /usr/local/bin/semaphore version
alpine3.18-92d935d-1687263070
```
```
# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.6
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

**Comment by fiftin** [comment]
Hi @cedbale currently Semaphore was built with Go 18.

We need to update Go version in GitHub Actions and go.mod.

**Comment by rehanone** [comment]
Is there a timeline for this PR? The current ansible version in the docker image is getting too old.

**Comment by fiftin** [comment]
Done

**Pull request closed without merging**
