### PR TITLE
Fixed SweetAlert confirmation popup

### PR DESCRIPTION
**Pull request by zarianec**
Related to #507

### CODE REVIEW

**Comment by fiftin** [comment]
@zarianec Invalid indentation style, you should use tabs instead of spaces.

**Comment by fiftin** [comment]
I think using angular wrapper for sweetalert is more preferable:

https://gist.github.com/pranav7/d075f7cd8263159cf36a

**Comment by zarianec** [comment]
Hi @fiftin, we are just discussing that in discord. Why tabs instead of spaces if spaces is widely used and is, de facto, standard for styling js code.
Angular uses 2 spaces as indentation. Also there is a style guides from google and airbnb that suggests using 2 spaces for indentation.
[Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)

**Comment by fiftin** [comment]
Tabs used in this project initially. The question should be addressed to @twhiston.

**Comment by zarianec** [comment]
Ok, i will convert spaces to tabs and open another issue related to code style.

**Comment by twhiston** [comment]
@zarianec thanks, that would be great. Let's pick a common and well know style guide in the new issue you create and then enforce it through the ci pipeline

**Comment by twhiston** [comment]
ii'll merge this and we can address angular wrapper stuff and style guide separately. Thanks

**Pull request merged**
