### PR TITLE
refactor: using OS instead of ioutil which is deprecated

### PR DESCRIPTION
**Pull request by Caixetadev**
This pr removes all ioutil that is deprecated and adds the OS in its place

### CODE REVIEW

**Review by tboerger — APPROVED** [review]
This really makes sense because of the deprecation.

**Comment by andreas-marschke** [comment]
Are the whitespace changes necessary? The change itself is A-OK It's just very cluttered.

**Comment by tboerger** [comment]
> Are the whitespace changes necessary? The change itself is A-OK It's just very cluttered.

That's simply what a proper IDE is doing. You can hide the whitespace changes if they annoy you by appending `?w=1` to the URL or by clicking on the settings icon within diff view and enabling "Hide whitespace".

**Comment by tboerger** [comment]
Sorry, #1818 have been merged instead of this pr.

**Pull request closed without merging**
