### PR TITLE
Refactor Interactive setup + formatting + windows development

### PR DESCRIPTION
**Pull request by zeroZshadow**
Refactored interactive setup to be in it's own file + have a more reasonable api.
Applied formatting to markdown and golang.
Fixed tests and setup for Windows.

### CODE REVIEW

**Comment by zeroZshadow** [comment]
Since I started this before the final fixes made last week, i'll have to do some puzzling with the conflicts, hopefully I have some time for this this weekend

**Comment by fiftin** [comment]
I like your Interactive setup refactoring. It really useful.
But I won't merge this PR because it contains a lot of useless changes (formatting, renaming, etc). It require review, but I have no time for this.
Sorry.

**Comment by zeroZshadow** [comment]
No worries, It was the intention to fix this.
Would you like me to split up the windows support and interaction into 2 PR's as well? Or is it oke to combine these?
I am on windows, so having these combined would be easiest for me.

**Comment by fiftin** [comment]
Single PR is ok, thank you!

**Comment by zeroZshadow** [comment]
I've re-done the changes to only include the minimum required bits.
There were some issues with the `go.sum as` `github.com/inconshreveable/mousetrap` was missing.

It might be good to add the tooling to a `tools.go` file that isn't included in the build so that they too get versioned through modules.

**Comment by fiftin** [comment]
Hi @zeroZshadow, thank you for PR.

**Comment by zeroZshadow** [comment]
Sorry about those 2 unused variables, seems I had overlooked them.
Do you happen to know why the entire file was marked as changed?
(perhaps changing newlines?)

**Comment by zeroZshadow** [comment]
I'm a little confused. Why the suddenly rename of all the methods, and changing it back to scanln?
bufio was specifically picked as it avoided newline errors on windows, which are now reintroduced.

Isn't the whole point of a PR that this could have been resolved through a code review?

I'll be moving on to a different ansible UI. Best of luck.

**Pull request merged**
