### PR TITLE
Slack alerts

### PR DESCRIPTION
**Pull request by wowi42**
The target was to create some Slack alerts, with 2 new parameters:

- slack_alert: true or false
- slack_url: the webhook, which means that this feature is also compatible with every slack-like system (Mattermost, Discord, etc...)

### CODE REVIEW

**Comment by anvme** [comment]
@fiftin When merge?)

**Comment by fiftin** [comment]
Hi @anvme ,

Thank you for your PR. But it require additional code for tests. You added `askConfirmation` to code but didn't modify Dockerfile for tests.

https://github.com/ansible-semaphore/semaphore/blob/32cc67164e279caef59529410e5dc714371ac4be/deployment/docker/common/semaphore-wrapper#L83

**Comment by YoungjuWang** [comment]
@wowi42 please check fiftin's comment. I'm waiting for your PR to be merged. Thanks.

**Comment by wowi42** [comment]
@YoungjuWang checking this week, I will let you know

**Comment by fiftin** [comment]
@wowi42 You just need to add line `no` after others `no` :)

**Comment by wowi42** [comment]
@fiftin done

**Pull request merged**
