### PR TITLE
added postgres and ldap support to compose #948

### PR DESCRIPTION
**Pull request by tiny-pangolin**
This exposes the postgres and ldap options in the dev config. I didn't add postgres to prod config since I have having issues with that setup in testing.

### CODE REVIEW

**Comment by fiftin** [comment]
Hi @tiny6996 

Did you test this changes?

**Comment by tiny-pangolin** [comment]
Yes I have tested this change with podmanc-compose and docker compose

**Comment by fiftin** [comment]
This docker-compose file used only for integration tests. We don't test LDAP.

I will add integration tests for all databases soon and we will have 3 docker compose files.

**Comment by fiftin** [comment]
I closing this PR, but I sure these changes should be reflected in the documentation.

Related to https://github.com/fiftin/ansible-semaphore-docs/issues/3.

Thank you!

**Pull request closed without merging**
