### PR TITLE
feat: added basic github issue-forms

### PR DESCRIPTION
**Pull request by ansibleguy**
Greetings!

I have created some basic [GitHub issue-forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).

This should help with:
* more users being able to solve their problems
* bringing more structure to created issues
* easier maintenance of existing issues

I would also suggest:
* creating the `triage` label that gets removed once a new issue has been checked by a repository maintainer (_filter for new tickets_)
* creating a workflow to [auto-close tickets that are inactive for N days](https://docs.github.com/en/github-ae@latest/actions/managing-issues-and-pull-requests/closing-inactive-issues)

### CODE REVIEW

**Comment by ansibleguy** [comment]
Related to: https://github.com/ansible-semaphore/semaphore/issues/1356

**Comment by steadfasterX** [comment]
awesome! really would love to see this added asap ;)

**Comment by ansibleguy** [comment]
@fiftin It seems the template are not active yet.
I've tested them on a private repo of mine - there they worked.
Could you check if they need to be enabled in the repository settings?
See: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by steadfasterX** [comment]
> is merging to branch develop correct?

nvm it should work as develop is the main branch.. so likely @fiftin really just must enable it

**Pull request merged**
