### PR TITLE
Add Ansible Vault Password Client Script support

### PR DESCRIPTION
**Pull request by Omicron7**
Implements #2359

This adds the ability to use Ansible Vault Password Client Script support for decrypting Ansible Vault. See https://docs.ansible.com/ansible/latest/vault_guide/vault_managing_passwords.html#storing-passwords-in-third-party-tools-with-vault-password-client-scripts

Script name must end in `-client` excluding the extension. Vault Passwords were switched from using `--ask-vault-pass` to `--vault-id=@prompt`. Client Scripts and Passwords were tested locally and are functioning properly.

### CODE REVIEW

**Comment by fiftin** [comment]
Hi @Omicron7 I like it! Thank you! I will test ASAP and will merge.

**Comment by fiftin** [comment]
@tboerger what do you think?

**Comment by tboerger** [comment]
It requires a database migration, right? Beside that it's looking good.

**Comment by Omicron7** [comment]
@tboerger No, this PR doesn't require a database migration. It utilizes the same `secret` column that the other Access Key types use.

**Comment by tboerger** [comment]
Oh, of course... It's marshalled... LGTM

**Review by tboerger — APPROVED** [review]

**Comment by fiftin** [comment]
Similar to https://github.com/semaphoreui/semaphore/pull/2392. Close.

**Comment by Omicron7** [comment]
@fiftin I agree, the PR's were similar, but they implemented different features (client scripts and multiple `--vault-id`). I'll rebase this and open another PR, unless you can reopen this one.

**Pull request closed without merging**
