### PR TITLE
Fixed mux router usage

### LINKED ISSUE #587: 404 not found on all delete and put api
I run semaphore --config config.json,  and service has been started. But there was something wrong with the put and delete api , they all returned 404 , but post and get api is normal.

image

image

### PR DESCRIPTION
**Pull request by megakoresh**
It seems that I misunderstood how mux works during my last work on routing refactor. This should fix #587 . I now understand better why mulekick was implemented. 

Not sure if the use of middleware in this project is idiomatic in golang (it seems logical to me, of course, but I come from Node.js background, where middleware for request context enrichment and policy control is the de-facto and most importantly - it's applied on separate routes, not router level). 

Seems kinda ugly and because you must split into a separate subrouter every time you need to change a middleware stack, tracking down route path becomes rather difficult (added a function print out registered paths for debugging purposes).

At any rate I don't feel comfortable refactoring this right now, so I just fixed the mux router usage.

@strangeman or @matejkramny can you pls do the honors?

### CODE REVIEW

**Comment by megakoresh** [comment]
I fixed the small issue preventing backend tests from running. Also can you disable the linting enforcement? Golint is not exactly the most trustworthy authority when it comes to code quality analysis.

**Comment by strangeman** [comment]
Something wrong - got infinite redirects on the main page (doesn't matter with or w/ trailing slash):

```
[semaphore]$ curl -v http://localhost:3000/
* About to connect() to localhost port 3000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:3000
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Type: application/json
< Location: /
< Date: Thu, 12 Sep 2019 01:43:34 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact

[semaphore]$ curl -v http://localhost:3000
* About to connect() to localhost port 3000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:3000
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Type: application/json
< Location: /
< Date: Thu, 12 Sep 2019 01:43:44 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Review by strangeman — CHANGES_REQUESTED** [review]
Current code cause infinite redirect loop

**Comment by megakoresh** [comment]
> Current code cause infinite redirect loop

Strange, man... Can't reproduce this. You get the same results with browser? How about with `curl -vL`? Will take a closer look when I get back from work today

**Comment by strangeman** [comment]
Yea, the same behavior in the browser too.

```
[semaphore]$ curl -vL http://localhost:3000
...
redirects
...
redirects
...
* Connection #0 to host localhost left intact
* Maximum (50) redirects followed
curl: (47) Maximum (50) redirects followed
```

**Comment by megakoresh** [comment]
I don't understand... I can't reproduce this at all. Tried with `task watch` as well as `task build:local` - it works just fine here:

```sh
$ megakoresh@DESKTOP-7OF5B73:/c/Users/megak/go/src/github.com/ansible-semaphore/semaphore$ curl -vL http://localhost:3000
* Rebuilt URL to: http://localhost:3000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html
< Date: Thu, 12 Sep 2019 15:50:46 GMT
< Transfer-Encoding: chunked
< 
<!DOCTYPE html><html lang="en" ng-app="semaphore"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8;"><meta name="viewport" content="width=device-width, initial-scale=1.0"><base href="/"><title ng-bind-template="{{ pageTitle }} - Semaphore">Semaphore</title><link href="/public/img/icon.png" type="image/png" rel="icon"><link href="/public/img/icon.png" type="image/png" rel="shortcut icon"><link rel="stylesheet" href="public/css/semaphore.css"></head><body><div class="navbar navbar-default" ng-if="loggedIn"><div class="container-fluid"><div class="navbar-header"><a class="navbar-brand" ui-sref="dashboard">semaphore</a></div><ul class="nav navbar-nav"><li ng-class="{ active: $state.includes('dashboard') }"><a ui-sref="dashboard">Dashboard</a></li><li ng-class="{ active: $state.includes('users') }"><a ui-sref="users.list">Users</a></li></ul><ul class="nav navbar-nav navbar-right" style="margin-right: 0;"><li ng-class="{ active: $state.includes('user') }"><a ui-sref="user"><i class="fa fa-fw fa-user"></i>&nbsp;{{ user.name }}</a></li><li uib-dropdown><a uib-dropdown-toggle><span ng-if="semaphore.update"><i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;</span><i class="fa fa-fw fa-cog"></i></a><ul uib-dropdown-menu><li class="dropdown-header">semaphore {{ semaphore.version }}</li><li><a ui-sref="admin"><span ng-if="semaphore.update"><i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;</span>System info</a></li><li class="divider"></li><li><a ui-sref="auth.logout"><i class="fa fa-fw fa-sign-out"></i>&nbsp;Log out</a></li></ul></li></ul></div></div><ui-view autoscroll="false"><p class="lead text-center"><i class="fa fa-spin fa-cog"></i> Loading...</p></ui-view><footer><a class="github-corner" href="https://github.com/ansible-semaphore/semaphore" target="_blank" title="Ansible-Semaphore on GitHub"><svg width="80" height="80" viewbox="0 0 250 250"><title>Ansible-Semaphore on GitHub</title><path d="M0 0h250v250"></path><path class="octo-arm" d="M127.4 110c-14.6-9.2-9.4-19.5-9.4-19.5 3-7 1.5-11 1.5-1* Connection #0 to host localhost left intact
1-1-6.2 3-2 3-2 4 4.7 2 11 2 11-2.2 10.4 5 14.8 9 16.2" fill="currentColor"></path><path class="octo-body" d="M113.2 114.3s3.6 1.6 4.7.6l15-13.7c3-2.4 6-3 8.2-2.7-8-11.2-14-25 3-41 4.7-4.4 10.6-6.4 16.2-6.4.6-1.6 3.6-7.3 11.8-10.7 0 0 4.5 2.7 6.8 16.5 4.3 2.7 8.3 6 12 9.8 3.3 3.5 6.7 8 8.6 12.3 14 3 16.8 8 16.8 8-3.4 8-9.4 11-11.4 11 0 5.8-2.3 11-7.5 15.5-16.4 16-30 9-40 .2 0 3-1 7-5.2 11l-13.3 11c-1 1 .5 5.3.8 5z" fill="currentColor"></path></svg></a></footer><script src="public/js/bundle.js"></script></body></html>
```

This is on commit `7f8f972ecc33e52378662288a3ec2accab86a63d` (Fixed repeating struct property). Are you running under windows? Anyone else experiencing this with my branch?

I also tried building under Linux and Windows, and still can't repro. Did you update your dependencies? Maybe something wrong with them?

**Comment by megakoresh** [comment]
Since I can only guess at this point, what may be the reason why you have a redirect loop, I have reverted to the old behaviour of relying on NotFoundHandler for serving static files. I really don't like this approach, and in general routing in golang seems like an awful exprerience. Just trying to get this working for now.

I will take a look at some more mature projects like mattermost later to see how they handle this on the backend.

UPD: Using mattermost server as [reference](https://github.com/mattermost/mattermost-server/tree/master/api4) - they use massive amouns of subrouters for every route namespace, then declare actual endpoints in the handler file using their own `http.Handler` implementation. However middleware is not used for policy control. In fact to me it seems that other than basic stuff like requiring authentication, which is handled by their `http.Handler` implementation, most of the authentication code is actually embedded directly in handler functions.

**Comment by strangeman** [comment]
I use Linux (Debian) and go go1.12.5 linux/amd64. Build with `task deps && task build:local`.

With last commit redirects are gone, I can see the main page, but without any content.
In semaphore logs I saw:
```
сен 13 07:46:22 dev5 semaphore_test[22556]: Executing migration v2.5.2 (at 2019-09-13 07:46:22.489252529 +0300 MSK m=+0.043551029)...
сен 13 07:46:26 dev5 semaphore_test[22556]: [1/1]
сен 13 07:46:26 dev5 semaphore_test[22556]: Migrations Finished
сен 13 07:47:42 dev5 semaphore_test[22556]: GET : https:///public/js/angular-ui-router.js.map --> 404 Not Found
сен 13 07:51:26 dev5 semaphore_test[22556]: GET : https:///public/js/angular-ui-router.js.map --> 404 Not Found
сен 13 07:52:53 dev5 semaphore_test[22556]: GET : https:///public/js/angular-ui-router.js.map --> 404 Not Found
сен 13 07:52:54 dev5 semaphore_test[22556]: GET : https:///public/js/angular-ui-router.js.map --> 404 Not Found
сен 13 07:53:42 dev5 semaphore_test[22556]: GET : https:///public/js/angular-ui-router.js.map --> 404 Not Found
```

**Comment by megakoresh** [comment]
> I use Linux (Debian) and go go1.12.5 linux/amd64. Build with `task deps && task build:local`.
> 
> With last commit redirects are gone, I can see the main page, but without any content.

I get content just fine and the application appears to be fully working (I tested routes manually since integration tests don't work). I also did a full golang reinstall, fully wiped all my `GOPATH` and environment, reinstalled dependencies from scratch (to ensure there is no cache anywhere), but I still can't repduce this.


Annotation 2019-09-13 184248
 
image

(the websocket thing is from when I logged out to title screen)

Did you do `task compile` before running?

**Comment by megakoresh** [comment]
Can someone else build my branch and check if they get the same issues? I cannot reproduce @strangeman 's problems on any of my computers.

**Comment by pedroelbanquero** [comment]
I add some changes in route.go , DELETE and PUT method not works in your version
here the link with the changes

#595

**Comment by pedroelbanquero** [comment]
> Current code cause infinite redirect loop

for me works in ubuntu all changes made by @megakoresh , just delete and put method fails, updated in my fork

**Review by pedroelbanquero — APPROVED** [review]
.

**Comment by megakoresh** [comment]
This is as far as I can get it I think. I have updated most build dependencies, migrated to golang's new module system, removed deprecated dependencies and fixed CI as much as I could. Integration tests still don't work, as it seems this dredd's request URI path is not being received properly, since every request is treated as a front page. Testing this myself with curl locally works just fine.

@strangeman 's problems did not appear and I have tested this now on CentOS, MacOS and Windows with @pedroelbanquero fixes the routes are working as expected. So unless someone else can also repro your problems, I think it's safe to say there's something wrong with your environment, since I see no reason for that kind of behavior, looking at the code.

I would also appreciate if @twhiston had a look at the updated images, since they had your label on them.

I don't have time to fix integration tests, since I have no experience with the dredd tool and it seems that it's golang's library is dead (no commits since 2017). So it's likely they won't work at all, maybe it needs another tool.

So unless someone can repro strangeman's issues, can either @matejkramny or him merge this please? I would be interested in developing some fixes and features for this project in the future, but that is blocked while the main branch is broken.

PS: thanks for the fixes, pedroelbanquero!

**Comment by pedroelbanquero** [comment]
> PS: thanks for the fixes, pedroelbanquero!

you are welcome . anyway im using now gitlab with ansible pipelines scheuldes. works really fine and have well support, I like this project because is really portable if you want to have your deployment kit or take as a base to develop another software.

**Pull request merged**
