### PR TITLE
dark mode

### PR DESCRIPTION
**Pull request by bakito**
add support for dark mode

### CODE REVIEW

**Comment by fiftin** [comment]
Why you closed PR? I think Dark mode is good idea.

**Comment by bakito** [comment]
@fiftin  It was not persistent.
Dark mod was always reset on reload.
I couldn't figure out how it could be persistent.
For that, my vue knowledge is not enough.

I could reopen it if you want to work further on it.

**Comment by fiftin** [comment]
Hi @bakito ,

State can be stored in localStorage. It is not part of vue.

**Comment by fiftin** [comment]
Thank you for PR, I will add missing functionality.

**Comment by bakito** [comment]
@fiftin cool, thank you very much

**Pull request merged**
