### PR TITLE
Bruteforce CI build to pass the project  

### PR DESCRIPTION
**Pull request by thapakazi**
_Motivation_
`Since the CI is failing since months, trying brute-force fix the build with dummy PR.`
trying_baby

_Behind the scene_
Landed to the project today, reloaded with positivity, free alternative for tower. Nice Nice.
Scrolling down, saw the red cross
screenshot-20161025-17 04 28

Tried the build stuffs in a container... but can't pass through 
:disappointed: :disappointed: :disappointed: 
and I am making this PR noise, to test and try fix CI builds :grimacing:  
## Apologies for blindly ignoring the PR guidelines.

**Rest of PR details is WIP (work in progress)**

### CODE REVIEW

**Comment by zerOnepal** [comment]
:fearful: 
Seems we are doint it wrong.
screenshot-20161025-17 09 45

**Comment by matejkramny** [comment]
Don't worry about the CI.

It has been broken for ages, but does not reflect the build-ability of the project.

There are install instructions in the wiki & the CI will be fixed in due course.

Cheers!

**Comment by brunowoo** [comment]
I tried fiddling with this myself a few days ago. The instructions it fails on are the installation commands for MySQL 5.6, which have become obsolete anyway as CircleCI now offers Ubuntu 14.04 which has MySQL 5.7 built-in. Removing the following two lines from circle.yml removes the error you show above:
    - sudo apt-add-repository -y 'deb http://ppa.launchpad.net/ondrej/mysql-experimental/ubuntu precise main'
    - sudo apt-get update; sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server-5.6

However, it then failed for me during the GOX compilation for darwin, for which I had not found a workaround yet (besides removing Darwin from the required OS')

**Comment by matejkramny** [comment]
We can also switch to the newer ubuntu image, which comes with mysql 5.6 by default I think.

**Comment by thapakazi** [comment]
😄 happy to see, green pass 🌲

**Pull request closed without merging**
